#ifndef __pro_litvinovg_libreoffice_hacksproject_idl__
#define __pro_litvinovg_libreoffice_hacksproject_idl__

#include <com/sun/star/task/XJobExecutor.idl>
module pro { module litvinovg { module libreoffice { 	

	service StarterProject : com::sun::star::task::XJobExecutor {

	};

 }; }; };
#endif
